version: '3.9'
services:
  auth_service:
    container_name: auth_service
    build:
      context: ./auth_service
    ports:
      - "5001:5001"
    command: npm run start

  main_service:
    container_name: main_service
    build:
      context: ./main_service
    ports:
      - "5000:5000"
    command: npm run start
    depends_on:
      - auth_service
