version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    ports:
      - '8000:8000'

  auth:
    build: ./auth
    restart: always
    ports:
      - '8001:8000'

  currency:
    build: ./currency
    restart: always
    ports:
      - '8002:8000'