version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npm run start
    ports:
      - 8000:8000
    restart: always

  auth:
    container_name: auth
    build:
      context: ./auth
    volumes:
      - ./auth:/app
      - /app/node_modules
    command: npm run start
    depends_on:
      - gateway
    ports:
      - 8001:8001
    restart: always

  meetings:
    container_name: meetings
    build:
      context: ./meetings
    depends_on:
      - gateway
    volumes:
      - ./meetings:/app
      - /app/node_modules
    command: npm run start
    ports:
      - 8002:8002
    restart: always
