version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npm run start
    ports:
      - 8000:8000
    restart: always
    networks:
      - mynetwork

  auth:
    container_name: auth
    build:
      context: ./auth
    volumes:
      - ./auth:/app
      - /app/node_modules
    depends_on:
      - gateway
    command: npm run start
    ports:
      - 8001:8001
    restart: always
    networks:
      - mynetwork

  exchange:
    container_name: exchange
    build:
      context: ./exchange
    depends_on:
      - gateway
    command: npm run start
    volumes:
      - ./exchange:/app
      - /app/node_modules
    ports:
      - 8002:8002
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
