name: Docker deploy 

on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#       - name: Login (Yandex Cloud)
#         id: login-cr
#         uses: yc-actions/yc-cr-login@v1
#         with:
#           yc-sa-json-credentials: ${{ secrets.AUTHORIZED_KEY }}

#       - name: Build image (Yandex Cloud)
#         env:
#           CR_REGISTRY: crp7qfv6r081t2ofp03o
#           CR_REPOSITORY: backend
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user$IMAGE_TAG ./homeworks/K33412/Tanachev\ Egor/HW6/task/user
#           docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user$IMAGE_TAG
#           docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:market$IMAGE_TAG ./homeworks/K33412/Tanachev\ Egor/HW6/task/market
#           docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:market$IMAGE_TAG
        
        
#       - name: Deploy VM (Yandex Cloud) 
#         uses: appleboy/ssh-action@v0.1.10 
#         env:
#           CR_REGISTRY: crp7qfv6r081t2ofp03o
#           CR_REPOSITORY: backend
#           IMAGE_TAG: ${{ github.sha }}
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           passphrase: ${{ secrets.PASSPHRASE }}
#           port: ${{ secrets.PORT }}
#           script: 
#             sudo docker kill $(docker ps -q) &> /dev/null
#             sudo docker rm $(docker ps -a -q) &> /dev/null
#             sudo docker run -dp 80:1111 cr.yandex/crp7qfv6r081t2ofp03o/backend:user5641985cef5d083145c3b0a099cf314e116fa755
#             sudo docker run -dp 80:2222 cr.yandex/crp7qfv6r081t2ofp03o/backend:market${{ github.sha }}





#       - name: Connect to VM via SSH
#         uses: appleboy/ssh-action@master
#         with:
#           host: 51.250.111.202
#           username: admin
#           key: ${{ secrets.KEY }}
#           passphrase: ${{ secrets.PASSPHRASE }}
#           port: 22

      - name: Run commands on VM 
        env:
           HOST: 51.250.111.202
           USERNAME: admin
           KEY: ${{ secrets.KEY }}
           PASSPHRASE: ${{ secrets.PASSPHRASE }}
           PORT: 22
           YANDEX_KEY: ${{ secrets.YANDEX_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST
          sudo docker login --username oauth --password $YANDEX_KEY cr.yandex
          sudo docker run -dp 80:1111 cr.yandex/crp7qfv6r081t2ofp03o/backend:user5641985cef5d083145c3b0a099cf314e116fa755
